Repository near/near-discovery, pull requests merged in 2023-11, with the labels that each got.

#796 Add /relayer-demo route
  src/data/bos-components.ts
  src/pages/relayer-demo.tsx
Labels: feature

#798 NEAR Org Landing Pages (Part 2 of 2)
  src/components/navigation/Navigation.tsx
  src/components/navigation/desktop/MainNavigationMenu.tsx
  src/components/navigation/navigation-categories.ts
  src/data/bos-components.ts
  src/pages/blockchain.tsx
  src/pages/data-availability.tsx
  src/pages/data-infrastructure.tsx
  src/pages/fast-auth-and-relayers.tsx
  src/pages/open-web-applications.tsx
Labels: enhancement

#800 Added Ledger to wallet selector
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: feature

#804 Promote idOS integration into production
  package.json
  pnpm-lock.yaml
  src/components/navigation/UserDropdownMenu.tsx
  src/components/vm/VmInitializer.tsx
  src/data/bos-components.ts
  src/hooks/useIdOS.ts
  src/pages/_app.tsx
  src/pages/settings.tsx
  src/stores/idosStore.ts
  src/styles/globals.css
  src/utils/types.ts
Labels: ignore-for-release

#808 Upgrade fast auth
  package.json
  pnpm-lock.yaml
Labels: enhancement

#815 develop -> main
  .github/release.yml
  package.json
  pnpm-lock.yaml
Labels: enhancement

#812 Reveal data availability link in header
  src/components/navigation/navigation-categories.ts
Labels: feature

#816 release DA link
  src/components/navigation/navigation-categories.ts
Labels: ignore-for-release

#809 chore: Bump `wallet-selector` to `8.7.1`
  package.json
  pnpm-lock.yaml
Labels: dependency

#819 chore: Bump `wallet-selector` to `8.7.2`
  package.json
  pnpm-lock.yaml
Labels: dependency

#826 chore: remove nearcon banner
  src/components/banners/NearconBanner.tsx
  src/components/navigation/desktop/DesktopNavigation.tsx
  src/components/navigation/mobile/Menu.tsx
Labels: enhancement

#821 Passed closeSearch function to close search UI
  src/components/navigation/desktop/TypeAheadDropdown.tsx
Labels: bug

#824 [WIP] epic template suggestions
  .github/ISSUE_TEMPLATE/epic.md
Labels: enhancement

#777 Added NearMobileWallet in wallet-selector
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: feature

#833 Update next.config.js
  next.config.js
Labels: enhancement

#834 promote /da shortcut
  next.config.js
Labels: ignore-for-release

#818 Save fork data
  src/components/sandbox/Navigation/NavigationRight.js
  src/components/sandbox/Sandbox.js
Labels: feature

#838 chore: bump sentry
  package.json
  pnpm-lock.yaml
Labels: dependency

#839 develop -> main
  package.json
  pnpm-lock.yaml
  src/components/navigation/icons/near-logo.svg
  src/components/sandbox/Navigation/NavigationRight.js
  src/components/sandbox/Sandbox.js
  src/pages/notifications.tsx
  src/utils/notifications.ts
Labels: ignore-for-release

#842 chore: bump near-social-vm
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#836 refactor: Change idOS data storage
  src/components/vm/VmInitializer.tsx
  src/hooks/useIdOS.ts
  src/pages/settings.tsx
  src/stores/idosStore.ts
Labels: enhancement

#850 chore: Update `wallet-selector` to `8.9.0`
  package.json
  pnpm-lock.yaml
Labels: dependency

#856 chore: switch html sanitization dependency
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: dependency

#857 develop -> main
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/hooks/useIdOS.ts
  src/pages/settings.tsx
  src/stores/idosStore.ts
Labels: ignore-for-release

#861 Temporarily disable api.near.social calls due to outage
  .idea/prettier.xml
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/s/[urlShareIndicator].tsx
Labels: bug

#862 Hotfix 11 29
  src/pages/[componentAccountId]/widget/[componentName].tsx
Labels: bug

#863 port hotfix to develop
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/s/[urlShareIndicator].tsx
Labels: bug

#858 horizon accelerator banner
  src/components/banner/Horizon.tsx
  src/components/navigation/desktop/DesktopNavigation.tsx
  src/components/navigation/mobile/Menu.tsx
  src/hooks/useBanner.ts
Labels: enhancement

#868 update the hzn link
  src/components/banner/Horizon.tsx
Labels: ignore-for-release

#870 develop -> main
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#871 chore: bump vm 2
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release
