Repository near/near-discovery, pull requests merged in 2024-03, with the labels that each got.

#1014 feat: create new events page
  src/data/bos-components.ts
  src/pages/[...arbitrary].tsx
  src/pages/events.tsx
  src/utils/config.ts
  src/utils/events.ts
Labels: enhancement

#1021 coordinating the deploy of the latest fast auth signer
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/data/bos-components.ts
  src/hooks/useSignInRedirect.ts
  src/pages/[...arbitrary].tsx
  src/pages/events.tsx
  src/utils/config.ts
  src/utils/events.ts
Labels: ignore-for-release

#1019 route existing sign in/up links to overlay the new auth modal on the applications page
  next.config.js
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/applications.tsx
Labels: feature

#1023 listen to route change events to track the referring url for client side routing
  src/pages/_app.tsx
  src/utils/analytics.ts
Labels: enhancement

#1026 develop -> main
  next.config.js
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/_app.tsx
  src/pages/applications.tsx
  src/utils/analytics.ts
Labels: ignore-for-release

#1024 fix: show fresh events
  package.json
  pnpm-lock.yaml
  src/utils/events.ts
Labels: enhancement

#1027 Analytics was opting out for all cases, fix to only optout if user chooses Only Required Cookies
  src/components/vm/VmInitializer.tsx
  src/utils/analytics.ts
Labels: bug

#1031 fix: redirect for the-official-near-white-paper
  public/files/the-official-near-white-paper.pdf
  src/pages/papers/index.tsx
Labels: enhancement

#1032 fix: redirect for the-official-near-white-paper
  public/files/the-official-near-white-paper.pdf
  src/pages/papers/index.tsx
Labels: ignore-for-release

#1033 hotfix: show file documents on standalone pages
  next.config.js
Labels: ignore-for-release

#1035 redirect this old blog which receives high traffic to more updated content
  next.config.js
Labels: ignore-for-release

#1003 geo boundary config for restricted areas
  src/middleware.ts
  src/pages/geoBlocked.tsx
  src/utils/analytics.ts
Labels: enhancement

#1036 fix: read cookie from cookies not local storage
  src/utils/analytics.ts
Labels: bug

#1042 chore: unfortunately we cannot auto copy the latest blogs without overwriting the manual link fixes
  package.json
Labels: ignore-for-release

#1044 fix: avoid triggering the sign-in modal if user has already authenticated
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/applications.tsx
Labels: bug

#1045 deploy sign-in loop fix
  package.json
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/applications.tsx
Labels: ignore-for-release

#1049 Fix dereference error
  src/data/web3.ts
Labels: ignore-for-release

#1052 Upgrading Dependencies + Lint Fix
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/components/sandbox/OnBoarding/Step3.js
  src/components/sandbox/OnBoarding/Step6.js
  src/components/sandbox/Sandbox.js
  src/components/sandbox/TabProps/index.js
  src/components/vm/VmInitializer.tsx
  src/hooks/useBosLoaderInitializer.ts
  src/hooks/useSignInRedirect.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/_app.tsx
  src/pages/applications.tsx
  src/pages/cookies/index.tsx
  src/pages/edit/index.tsx
  src/pages/events.tsx
  src/pages/founders.tsx
  src/pages/notifications.tsx
  src/pages/relayer-demo.tsx
  src/pages/s/[urlShareIndicator].tsx
  src/pages/settings.tsx
  src/pages/signMessage.tsx
  src/pages/signup.tsx
  src/utils/notifications.ts
  src/utils/route/privateRoute.tsx
Labels: ignore-for-release

#1046 fix: Update canonical reference link on _app.tsx
  src/pages/_app.tsx
Labels: bug

#1054 when a firebase auth error occurs, users will be informed via a toast message
  src/pages/_app.tsx
Labels: enhancement

#1055 chore: update to reference large bandwidth files from pages.near.org
  public/blog/community-update-zest-hack-the-rainbow/index.html
  public/blog/press-releases-categories/ecosystem/index.html
  public/blog/press-releases-categories/governance/index.html
  public/blog/press-releases-categories/inclusion/index.html
  public/blog/press-releases-categories/other/index.html
  public/blog/press-releases-categories/partner/index.html
  public/blog/press-releases-categories/partner/page/2/index.html
  public/blog/press-releases-categories/regional-hubs/index.html
  public/blog/press-releases-categories/technical/index.html
  public/blog/welcome-to-near-con/index.html
Labels: enhancement

#1057 fix: regression in routes to technical papers
  next.config.js
  src/pages/papers/index.tsx
Labels: bug

#1062 sitemap and http redirect updates targeting seo improvements
  next.config.js
  src/pages/sitemap.xml.tsx
Labels: dependency

#1073 chore: remove unnecessary wrapper from `NotificationButton`
  src/components/navigation/NotificationButton.tsx
Labels: enhancement

#1074 non-regular promotion develop -> main
  src/components/navigation/NotificationButton.tsx
Labels: ignore-for-release

#1081 Updated Near's meta tagline and thumbnail image
  public/bos-meta.png
  public/manifest.json
  public/near-meta.png
  src/components/MetaTags.tsx
  src/pages/index.tsx
Labels: enhancement

#1082 deploy updated meta
  public/bos-meta.png
  public/manifest.json
  public/near-meta.png
  src/components/MetaTags.tsx
  src/pages/index.tsx
Labels: ignore-for-release

#1069 New Navigation Layout (Sidebar)
  .env.example
  package.json
  pnpm-lock.yaml
  src/components/CookiePrompt.tsx
  src/components/layouts/DefaultLayout.tsx
  src/components/lib/Container/Container.tsx
  src/components/lib/Container/index.ts
  src/components/lib/Tooltip/README.md
  src/components/lib/Tooltip/Tooltip.tsx
  src/components/lib/Tooltip/index.ts
  src/components/lib/Tooltip/styles.ts
  src/components/marketing-navigation/CurrentComponent.tsx
  src/components/marketing-navigation/MarketingNavigation.tsx
  src/components/marketing-navigation/NotificationButton.tsx
  src/components/marketing-navigation/UserDropdownMenu.tsx
  src/components/marketing-navigation/categories.ts
  src/components/marketing-navigation/desktop/DesktopNavigation.tsx
  src/components/marketing-navigation/desktop/MainNavigationMenu.tsx
  src/components/marketing-navigation/desktop/TypeAheadDropdown.tsx
  src/components/marketing-navigation/icons/close.svg
  src/components/marketing-navigation/icons/near-icon.svg
  src/components/marketing-navigation/icons/near-logo.svg
  src/components/marketing-navigation/icons/return.svg
  src/components/marketing-navigation/icons/search.svg
  src/components/marketing-navigation/mobile/AccordionMenu.tsx
  src/components/marketing-navigation/mobile/Menu.tsx
  src/components/marketing-navigation/mobile/MobileNavigation.tsx
  src/components/near-org/ComponentWrapperPage.tsx
  src/components/sidebar-navigation/DiscoverDrawer.tsx
  src/components/sidebar-navigation/DrawerHeader.tsx
  src/components/sidebar-navigation/LargeScreenHeader.tsx
  src/components/sidebar-navigation/LargeScreenNotificationButton.tsx
  src/components/sidebar-navigation/LargeScreenProfileDropdown.tsx
  src/components/sidebar-navigation/MarketingDrawer.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SidebarNavigation.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/icons/near-icon.svg
  src/components/sidebar-navigation/icons/near-logo.svg
  src/components/sidebar-navigation/sections.ts
  src/components/sidebar-navigation/store.ts
  src/components/sidebar-navigation/styles.ts
  src/components/sidebar-navigation/utils.ts
  src/components/vm/VmComponent.tsx
  src/data/bos-components.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/_app.tsx
  src/pages/activity.tsx
  src/pages/bosblog/index.tsx
  src/pages/flags.tsx
  src/pages/geoBlocked.tsx
  src/pages/signMessage.tsx
  src/styles/globals.css
  src/styles/theme.css
  src/utils/config.ts
  tsconfig.json
Labels: feature

#1083 Minor CSS Sidebar Fixes
  src/components/sidebar-navigation/styles.ts
  src/styles/globals.css
Labels: ignore-for-release

#1084 feat: add new Horizon banner
  src/components/banner/Horizon.tsx
  src/components/lib/Button/Button.tsx
  src/components/marketing-navigation/desktop/DesktopNavigation.tsx
  src/components/marketing-navigation/mobile/MobileNavigation.tsx
Labels: enhancement

#1088 fix: update blog to pass in contributors
  src/pages/bosblog/index.tsx
Labels: enhancement

#1093 Sync Home Page Events (1/2)
  src/pages/index.tsx
Labels: enhancement

#1092 fix: fix truthy check to ensure signup/signup redirect shows modal
  src/pages/applications.tsx
Labels: bug
