Repository near/near-discovery, pull requests merged in 2024-02, with the labels that each got.

#953 adding events to report on caught errors
  src/components/sandbox/Sandbox.js
  src/components/sandbox/TabProps/index.js
  src/components/vm/VmInitializer.tsx
  src/hooks/useBosLoaderInitializer.ts
  src/hooks/useIdOS.ts
  src/pages/settings.tsx
  src/pages/signup.tsx
  src/utils/analytics.ts
  src/utils/notifications.ts
Labels: enhancement

#956 develop -> main
  next.config.js
  src/components/sandbox/Sandbox.js
  src/components/sandbox/TabProps/index.js
  src/components/vm/VmInitializer.tsx
  src/hooks/useBosLoaderInitializer.ts
  src/hooks/useIdOS.ts
  src/pages/[...arbitrary].tsx
  src/pages/settings.tsx
  src/pages/signup.tsx
  src/utils/analytics.ts
  src/utils/notifications.ts
Labels: ignore-for-release

#323 introduce pwa configs
  .gitignore
  next.config.js
  package.json
  pnpm-lock.yaml
  public/logo512.png
  public/manifest.json
  public/pwa.js
  public/service-worker.js
  public/site.webmanifest
  src/pages/_app.tsx
Labels: enhancement

#957 service worker cleanup & link update
  next.config.js
  public/push-notifications.js
  src/data/bos-components.ts
  src/pages/signup.tsx
  src/utils/notifications.ts
Labels: feature

#961 chore: Updated wallet-selector to 8.9.4
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: dependency

#963 chore: Updated wallet-selector to 8.9.5
  package.json
  pnpm-lock.yaml
Labels: dependency

#965 fix: update github link to point to org readme
  src/components/navigation/navigation-categories.ts
Labels: documentation, enhancement

#971 feat: create a new `papers` page
  public/files/doomslug.pdf
  public/files/nightshade.pdf
  public/files/white-paper-near-protocol.pdf
  src/components/navigation/navigation-categories.ts
  src/data/bos-components.ts
  src/pages/[...arbitrary].tsx
  src/pages/papers/index.tsx
Labels: enhancement

#969 chore: Update sitemap for improving SEO
  public/robots.txt
  src/pages/sitemap.xml.tsx
Labels: dependency

#967 feat: add mintbase wallet support
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: feature

#954 Vm error callback
  src/components/vm/VmInitializer.tsx
Labels: enhancement

#973 build: trigger prod releases branches on Tuesdays and Thursdays
  .github/workflows/promote-develop-to-main.yml
Labels: ignore-for-release

#980 route to /papers/nightshade
  next.config.js
Labels: bug

#981 fix near.org/papers/nightshade
  next.config.js
Labels: bug

#984 chore: remove blankspace sitemap.xml.tsx
  src/pages/sitemap.xml.tsx
Labels: dependency

#985 build: workflow that generates a detailed release on merges to master
  .github/workflows/release_notes.yml
Labels: ignore-for-release

#986 feat: update nighshade to v2.0
  public/files/nightshade.pdf
Labels: documentation, enhancement

#987 style updates and reduction of links in the navigation menu
  src/components/navigation/desktop/MainNavigationMenu.tsx
  src/components/navigation/mobile/AccordionMenu.tsx
  src/components/navigation/navigation-categories.ts
  src/hooks/useBosLoaderInitializer.ts
Labels: enhancement

#982 feat: update route to founders page
  next.config.js
  src/components/navigation/navigation-categories.ts
  src/data/bos-components.ts
  src/pages/founders.tsx
  src/utils/zendesk.ts
Labels: enhancement

#989 setup a homepage for ETHDenver
  next.config.js
Labels: enhancement

#990 develop -> main
  next.config.js
  src/components/navigation/desktop/MainNavigationMenu.tsx
  src/components/navigation/mobile/AccordionMenu.tsx
  src/components/navigation/navigation-categories.ts
  src/data/bos-components.ts
  src/hooks/useBosLoaderInitializer.ts
  src/pages/founders.tsx
  src/utils/zendesk.ts
Labels: ignore-for-release

#929 Put fast-auth-signer in iframe for authentication process.
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/hooks/useSignInRedirect.ts
Labels: enhancement

#991 feat: landing page where we can iterate on the new blog
  src/data/bos-components.ts
  src/pages/bosblog/index.tsx
Labels: feature

#996 Revert "Put fast-auth-signer in iframe for authentication process."
  .gitignore
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/hooks/useSignInRedirect.ts
Labels: bug

#1000 Provides a custom component to a BOS Custom cookie prompt to replace the iubenda plugin
  src/components/vm/VmInitializer.tsx
  src/data/bos-components.ts
  src/hooks/useCookiePreferences.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/_app.tsx
  src/utils/analytics.ts
  src/utils/types.ts
Labels: feature

#1004 fix the use of the deprecated style to pass variables between action steps
  .github/workflows/release_notes.yml
Labels: ignore-for-release

#1013 update to the vm release 2.6.0
  package.json
  pnpm-lock.yaml
Labels: enhancement
