Repository near/near-discovery, pull requests merged in 2024-10, with the labels that each got.

#1313 New Landing Page
  package.json
  pnpm-lock.yaml
  src/assets/images/wallets/binance.webp
  src/assets/images/wallets/bitget.webp
  src/assets/images/wallets/bitte.svg
  src/assets/images/wallets/here.svg
  src/assets/images/wallets/index.ts
  src/assets/images/wallets/ledger.webp
  src/assets/images/wallets/metamask.webp
  src/assets/images/wallets/meteor.png
  src/assets/images/wallets/myNear.png
  src/assets/images/wallets/safePal.webp
  src/assets/images/wallets/sender.png
  src/assets/images/wallets/trustWallet.webp
  src/assets/images/wallets/uniswap.webp
  src/components/home/Button.tsx
  src/components/home/ChainAbstraction/index.tsx
  src/components/home/Code.tsx
  src/components/home/Contracts/index.tsx
  src/components/home/Data/index.tsx
  src/components/home/DecentralizedApps/index.tsx
  src/components/sandbox/Sandbox.js
  src/components/sidebar-navigation/Sidebar.tsx
  src/hooks/useDeviceType.ts
  src/pages/index.tsx
  src/pages/onboarding/[...componentSrc].tsx
  src/pages/onboarding/index.tsx
  src/pages/sandbox/[...componentSrc].tsx
  src/pages/sandbox/index.tsx
  src/styles/globals.css
Labels: breaking-change

#1316 VM Fixes
  pnpm-lock.yaml
  src/components/near-org/ComponentWrapperPage.tsx
  src/data/links.ts
  src/hooks/useClearCurrentComponent.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/cookies/index.tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/flags.tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/stores/current-component.ts
Labels: bug

#1317 Push fix to main
  pnpm-lock.yaml
  src/components/near-org/ComponentWrapperPage.tsx
  src/data/links.ts
  src/hooks/useClearCurrentComponent.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/cookies/index.tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/flags.tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/stores/current-component.ts
Labels: ignore-for-release

#1318 feat: remove server side load
  package.json
  pnpm-lock.yaml
  src/components/sidebar-navigation/UserDropdownMenu.tsx
  src/pages/[accountId]/widget/[componentName].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
Labels: breaking-change

#1319 Deploy to main
  package.json
  pnpm-lock.yaml
  src/components/sidebar-navigation/UserDropdownMenu.tsx
  src/pages/[accountId]/widget/[componentName].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
Labels: ignore-for-release

#1322 fix: collection of small fixes
  package.json
  pnpm-lock.yaml
  src/components/wallet-selector/WalletSelector.ts
  src/components/wallet-utilities/ExportFastAuthAccount.tsx
  src/components/wallet-utilities/ReceiveNear.tsx
  src/components/wallet-utilities/SendNear.tsx
  src/pages/[accountId]/widget/[componentName].tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/utils/algoliaSearchApi.ts
  src/utils/catalogSearchApi.ts
Labels: bug

#1323 Minor Fixes - Promote develop to main
  package.json
  pnpm-lock.yaml
  src/components/wallet-selector/WalletSelector.ts
  src/components/wallet-utilities/ExportFastAuthAccount.tsx
  src/components/wallet-utilities/ReceiveNear.tsx
  src/components/wallet-utilities/SendNear.tsx
  src/pages/[accountId]/widget/[componentName].tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/index.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/utils/algoliaSearchApi.ts
  src/utils/catalogSearchApi.ts
Labels: ignore-for-release

#1312 Clear and fix linkdrops
  next.config.js
  src/assets/images/near-icon.svg
  src/assets/images/token_default.svg
  src/components/NTFImage.tsx
  src/components/RoundedImage.tsx
  src/components/sidebar-navigation/UserDropdownMenu.tsx
  src/components/tools/FungibleToken/CreateTokenForm.tsx
  src/components/tools/FungibleToken/ListToken.tsx
  src/components/tools/FungibleToken/index.tsx
  src/components/tools/Linkdrops/CreateNFTDrop.tsx
  src/components/tools/Linkdrops/CreateTokenDrop.tsx
  src/components/tools/Linkdrops/ListTokenDrop.tsx
  src/components/tools/Linkdrops/SelectFT.tsx
  src/components/tools/Linkdrops/index.tsx
  src/components/tools/NonFungibleToken/CommunityTools.tsx
  src/components/tools/NonFungibleToken/ListToken.tsx
  src/components/tools/NonFungibleToken/MintNft.tsx
  src/components/tools/NonFungibleToken/index.tsx
  src/components/tools/Shared/Carousel.tsx
  src/components/wallet-selector/WalletSelector.ts
  src/config.ts
  src/hooks/useLinkdrops.ts
  src/hooks/useNFT.ts
  src/hooks/useNearBlocksTxns.ts
  src/pages/tools.tsx
  src/styles/globals.css
  src/utils/linkdrops.ts
  src/utils/types.ts
  src/utils/white-list.json
Labels: enhancement

#1324 Toolbox
  next.config.js
  src/assets/images/near-icon.svg
  src/assets/images/token_default.svg
  src/components/NTFImage.tsx
  src/components/RoundedImage.tsx
  src/components/sidebar-navigation/UserDropdownMenu.tsx
  src/components/tools/FungibleToken/CreateTokenForm.tsx
  src/components/tools/FungibleToken/ListToken.tsx
  src/components/tools/FungibleToken/index.tsx
  src/components/tools/Linkdrops/CreateNFTDrop.tsx
  src/components/tools/Linkdrops/CreateTokenDrop.tsx
  src/components/tools/Linkdrops/ListTokenDrop.tsx
  src/components/tools/Linkdrops/SelectFT.tsx
  src/components/tools/Linkdrops/index.tsx
  src/components/tools/NonFungibleToken/CommunityTools.tsx
  src/components/tools/NonFungibleToken/ListToken.tsx
  src/components/tools/NonFungibleToken/MintNft.tsx
  src/components/tools/NonFungibleToken/index.tsx
  src/components/tools/Shared/Carousel.tsx
  src/components/wallet-selector/WalletSelector.ts
  src/config.ts
  src/hooks/useLinkdrops.ts
  src/hooks/useNFT.ts
  src/hooks/useNearBlocksTxns.ts
  src/pages/tools.tsx
  src/styles/globals.css
  src/utils/linkdrops.ts
  src/utils/types.ts
  src/utils/white-list.json
Labels: enhancement

#1325 Developer Toolbox
  next.config.js
  src/assets/images/near-icon.svg
  src/assets/images/token_default.svg
  src/components/NTFImage.tsx
  src/components/RoundedImage.tsx
  src/components/sidebar-navigation/UserDropdownMenu.tsx
  src/components/tools/FungibleToken/CreateTokenForm.tsx
  src/components/tools/FungibleToken/ListToken.tsx
  src/components/tools/FungibleToken/index.tsx
  src/components/tools/Linkdrops/CreateNFTDrop.tsx
  src/components/tools/Linkdrops/CreateTokenDrop.tsx
  src/components/tools/Linkdrops/ListTokenDrop.tsx
  src/components/tools/Linkdrops/SelectFT.tsx
  src/components/tools/Linkdrops/index.tsx
  src/components/tools/NonFungibleToken/CommunityTools.tsx
  src/components/tools/NonFungibleToken/ListToken.tsx
  src/components/tools/NonFungibleToken/MintNft.tsx
  src/components/tools/NonFungibleToken/index.tsx
  src/components/tools/Shared/Carousel.tsx
  src/components/wallet-selector/WalletSelector.ts
  src/config.ts
  src/hooks/useLinkdrops.ts
  src/hooks/useNFT.ts
  src/hooks/useNearBlocksTxns.ts
  src/pages/tools.tsx
  src/styles/globals.css
  src/utils/linkdrops.ts
  src/utils/types.ts
  src/utils/white-list.json
Labels: enhancement

#1326 fixes
  src/components/tools/FungibleToken/CreateTokenForm.tsx
  src/pages/tools.tsx
  src/styles/globals.css
Labels: enhancement

#1328 fix: styles issue on home page for Safari 17
  src/components/home/Contracts/index.tsx
  src/components/home/DecentralizedApps/index.tsx
Labels: bug

#1329 Feat/add selector network
  src/components/sidebar-navigation/Search.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
Labels: feature

#1330 feat: new login modal
  src/assets/images/wallets/fastAuth.png
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/wallet-selector/WalletSelector.ts
  src/hooks/useSignInRedirect.ts
  src/pages/[accountId]/widget/[componentName].tsx
  src/pages/applications.tsx
  src/pages/wallet-utilities.tsx
  src/styles/globals.css
Labels: enhancement
