Repository near/near-discovery, pull requests merged in 2024-06, with the labels that each got.

#1186 update the custom `Link` component for functionality parity with near.social
  src/components/vm/VmInitializer.tsx
Labels: enhancement

#1199 feat: simplified menu
  src/components/layouts/DefaultLayout.tsx
  src/components/sidebar-navigation/DiscoverDrawer.tsx
  src/components/sidebar-navigation/LargeScreenNameDropdown.tsx
  src/components/sidebar-navigation/MarketingDrawer.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SidebarNavigation.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
  src/data/bos-components.ts
  src/pages/documentation.tsx
Labels: enhancement

#1212 feat: upgrade to near-fastauth-wallet 0.1.0 to get signMessage feature
  package.json
  pnpm-lock.yaml
Labels: feature

#1209 Change login button color
  src/components/sidebar-navigation/styles.ts
Labels: enhancement

#1218 revert fastauth-wallet upgrade
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1220 update dns from audit to assessment
  next.config.js
Labels: enhancement

#1222 Support testing blog content by toggling the github branch used for blog content based on the current environment
  src/pages/blog/[[...pages]].tsx
Labels: enhancement

#1219 chore: reduce amount of search categories (Part 2/2)
  src/components/layouts/DefaultLayout.tsx
  src/components/sidebar-navigation/LargeScreenHeader.tsx
  src/components/sidebar-navigation/LargeScreenProfileDropdown.tsx
  src/components/sidebar-navigation/Search.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
Labels: enhancement

#1231 feat: adds tooltip and expands sidebar on click
  src/components/sidebar-navigation/Sidebar.tsx
Labels: enhancement

#1232 build: bump fastauth wallet to pick up the signMessage ability
  package.json
  pnpm-lock.yaml
Labels: dependency

#1233 deploy search UX improvement
  package.json
  pnpm-lock.yaml
  src/components/sidebar-navigation/Sidebar.tsx
Labels: ignore-for-release
