Repository near/near-discovery, pull requests merged in 2024-05, with the labels that each got.

#1153 feat: enable new homepage
  src/components/layouts/DefaultLayout.tsx
  src/components/sidebar-navigation/DiscoverDrawer.tsx
  src/components/sidebar-navigation/MarketingDrawer.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/sections.ts
  src/components/sidebar-navigation/styles.ts
  src/pages/index.tsx
Labels: enhancement

#1157 feat: update shared url to handle reposts
  src/pages/s/[urlShareIndicator].tsx
Labels: enhancement

#1155 alert wallet-connected users of the move to dev.near.org
  src/components/DevNearOrgMigration.tsx
  src/components/lib/Toast/store.ts
  src/pages/_app.tsx
Labels: enhancement

#1160 add subdirectory redirect to airtable form for audit program
  next.config.js
Labels: feature

#1168 chore: update tooltip to include path & search params
  src/components/DevNearOrgMigration.tsx
Labels: ignore-for-release

#1169 chore: remove the horizon banner
  src/components/marketing-navigation/desktop/DesktopNavigation.tsx
  src/components/marketing-navigation/mobile/MobileNavigation.tsx
Labels: enhancement

#1172 Adds queryAPI into the sidebar navigation of dev.near.org
  src/components/sidebar-navigation/sections.ts
Labels: enhancement

#1173 Conditionally render NearOrg.Footer on BlogPostPage (2 of 2)
  src/pages/bosblog/index.tsx
Labels: bug

#1175 feat: allow for gateway to pass in url for bosblog component
  src/pages/bosblog/index.tsx
Labels: enhancement

#1177 feat: implement migration to dev.near.org banner
  src/components/DevNearOrgMigration.tsx
  src/components/banner/MigrationBanner.tsx
  src/components/marketing-navigation/desktop/DesktopNavigation.tsx
  src/components/marketing-navigation/mobile/MobileNavigation.tsx
  src/pages/_app.tsx
Labels: enhancement

#1178 Adding back metadata SSR logic when viewing a component page
  src/pages/[componentAccountId]/widget/[componentName].tsx
Labels: bug

#1181 adds a 'View Component' alternative for dev.near.org
  src/components/sidebar-navigation/MarketingDrawer.tsx
Labels: enhancement

#1183 a more stable implemention of the dynamic More->Develop->Inspect menu option
  src/components/sidebar-navigation/MarketingDrawer.tsx
Labels: enhancement

#1184 deploy fix for Inspect Component
  src/components/sidebar-navigation/MarketingDrawer.tsx
Labels: ignore-for-release

#1187 chore: add idos create account link (2 of 2)
  .env.example
  src/pages/settings.tsx
  src/utils/config.ts
Labels: ignore-for-release

#1189 chore: temporarily move to dev branch of near-social-vm
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release
