Repository near/near-discovery, pull requests merged in 2024-04, with the labels that each got.

#1101 feat: make new home page visible along with sidebar
  src/components/layouts/DefaultLayout.tsx
  src/components/sidebar-navigation/hooks.ts
  src/data/bos-components.ts
  src/pages/index.tsx
Labels: ignore-for-release

#1103 Pinned Apps (2 of 2)
  src/components/lib/Text/Text.tsx
  src/components/near-org/ComponentWrapperPage.tsx
  src/components/sidebar-navigation/PinnedApps.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/store.ts
  src/components/sidebar-navigation/styles.ts
  src/components/sidebar-navigation/utils.ts
  src/components/vm/VmInitializer.tsx
  src/hooks/useGatewayEvents.ts
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/index.tsx
  src/pages/s/[urlShareIndicator].tsx
  src/styles/globals.css
Labels: feature

#1105 Fix ?sidebar=true test flag
  src/components/sidebar-navigation/hooks.ts
Labels: ignore-for-release

#1108 Fixing sidebar query param
  src/components/sidebar-navigation/hooks.ts
Labels: ignore-for-release

#1114 adds a nav item to infra's zendesk support
  .github/release.yml
  .github/workflows/prs_must_have_labels.yml
  src/components/marketing-navigation/categories.ts
Labels: documentation

#1111 feat: create metadata handler for blogposts
  src/pages/s/[urlShareIndicator].tsx
Labels: feature

#1115 Contact Us Page (2 of 2)
  src/components/marketing-navigation/categories.ts
  src/components/sidebar-navigation/sections.ts
  src/data/bos-components.ts
  src/pages/contact-us.tsx
Labels: feature

#1112 feat: use `actionAtBlockHeight` to generate link for push notification
  public/push-notifications.js
Labels: enhancement

#1122 chore: set pnpm version for CI to 8.5.1
  .github/workflows/continuous-integration-workflow.yml
Labels: ignore-for-release

#1120 Reference the new contact-us page in the sidebar nav
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/sections.ts
Labels: ignore-for-release

#1123 chore: bump version of ci tools which has deprecated dependencies
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/promote-develop-to-main.yml
  .github/workflows/release_notes.yml
Labels: dependency

#1124 chore: update `wallet-selector` to `8.9.7`
  package.json
  pnpm-lock.yaml
Labels: dependency

#1119 Add debug, error logs for push notifications and update the service-worker's scope
  public/push/push-notifications.js
  src/utils/config.ts
  src/utils/notifications.ts
Labels: ignore-for-release

#1128 chore: make the localStorage notification data easy to understand
  src/utils/notificationsLocalStorage.ts
Labels: ignore-for-release

#1135 update to the latest vm release
  package.json
  pnpm-lock.yaml
Labels: dependency

#1138 chore: upgrade to phosphor icons 2.1.0
  src/pages/_app.tsx
Labels: enhancement

#1139 chore: safely update dependencies
  package.json
  pnpm-lock.yaml
Labels: dependency

#1140 chore: update commit script
  .husky/pre-commit
  src/pages/s/[urlShareIndicator].tsx
Labels: enhancement

#1141 chore: update `commitlint` module
  package.json
  pnpm-lock.yaml
Labels: dependency

#1143 chore: update `near-fastauth-wallet`
  package.json
  pnpm-lock.yaml
Labels: dependency

#1147 Fix component reference on testnet
  src/data/bos-components.ts
Labels: enhancement

#1151 Cleanup unused things
  .env.example
  .github/workflows/update_submodules.yml
Labels: ignore-for-release
