Repository near/near-discovery, pull requests merged in 2024-08, with the labels that each got.

#1282 Prevent bad phospor imports
  next.config.js
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  tsconfig.json
Labels: dependency

#1284 promote develop
  next.config.js
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  tsconfig.json
Labels: ignore-for-release

#1272 fix: only initialize gleap after developer survey and cookie promp
  src/components/CookiePrompt.tsx
  src/components/research-form-wizard/ResearchFormWizard.tsx
  src/components/vm/VmInitializer.tsx
  src/hooks/useCookiePreferences.ts
  src/hooks/useResearchWizardEvents.tsx
  src/pages/_app.tsx
  src/stores/cookieData.ts
  src/stores/researchWizard.tsx
Labels: bug

#1288 Upgrade UI lib to 0.3.0 for reduced package size
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#1280 feat: add events page
  .env.example
  src/components/sidebar-navigation/Sidebar.tsx
  src/hooks/useEvents.ts
  src/hooks/useGoogleEvents.ts
  src/hooks/useLumaEvents.ts
  src/pages/events.tsx
  src/pages/index.tsx
  src/utils/config.ts
  src/utils/events.ts
  src/utils/types.ts
Labels: feature

#1290 Improve the Label checker
  .github/workflows/prs_must_have_labels.yml
  package.json
Labels: dependency

#1293 Upgrade UI library to 1.0.0
  package.json
  pnpm-lock.yaml
  src/components/CookiePrompt.tsx
  src/components/research-form-wizard/ResearchFormWizard.tsx
  src/components/vm/VmInitializer.tsx
  src/hooks/useResearchWizardEvents.tsx
  src/pages/_app.tsx
Labels: ignore-for-release

#1299 Promote develop to main
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/utils/catalogSearchApi.ts
Labels: ignore-for-release

#1287 Reduce dependency on the VM
  package.json
  pnpm-lock.yaml
  src/components/NTFImage.tsx
  src/components/NotificationsAlert.tsx
  src/components/WalletSelector.ts
  src/components/banner/MigrationBanner.tsx
  src/components/marketing-navigation/UserDropdownMenu.tsx
  src/components/marketing-navigation/desktop/DesktopNavigation.tsx
  src/components/marketing-navigation/mobile/Menu.tsx
  src/components/marketing-navigation/mobile/MobileNavigation.tsx
  src/components/sandbox/Sandbox.js
  src/components/sidebar-navigation/LargeScreenHeader.tsx
  src/components/sidebar-navigation/LargeScreenNameDropdown.tsx
  src/components/sidebar-navigation/PinnedApps.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
  src/components/vm/VM.tsx
  src/components/vm/VmComponent.tsx
  src/components/vm/VmInitializer.tsx
  src/components/wallet-utilities/ExportFastAuthAccount.tsx
  src/components/wallet-utilities/KeyTable.tsx
  src/components/wallet-utilities/ReceiveNear.tsx
  src/components/wallet-utilities/SendNear.tsx
  src/hooks/useSignInRedirect.ts
  src/pages/[...arbitrary].tsx
  src/pages/[componentAccountId]/widget/[componentName].tsx
  src/pages/_app.tsx
  src/pages/applications.tsx
  src/pages/embed/[accountId]/widget/[componentName].tsx
  src/pages/index.tsx
  src/pages/notifications-settings.tsx
  src/pages/notifications.tsx
  src/pages/relayer-demo.tsx
  src/pages/settings.tsx
  src/pages/signMessage.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/pages/wallet-utilities.tsx
  src/stores/auth.ts
  src/utils/route/privateRoute.tsx
  src/utils/route/signedOutRoute.tsx
Labels: breaking-change

#1301 Expose `setURLSearchParams` and `scrollTo` functions to Applications page (NEAR Catalog component)
  src/pages/applications.tsx
Labels: enhancement

#1302 Mint nft tool added
  src/assets/images/mintbase.svg
  src/assets/images/paras.svg
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/tools/MintNft.tsx
  src/components/tools/NonFungibleToken.tsx
  src/pages/tools.tsx
Labels: feature

#1304 fix: import router query as component props in applications page
  src/pages/applications.tsx
Labels: bug
