Repository near/near-discovery, pull requests merged in 2024-07, with the labels that each got.

#1235 Style fixes
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/styles.ts
Labels: enhancement

#1236 Navigated links documentation
  src/pages/documentation.tsx
  src/pages/documentation/[[...slug]].tsx
Labels: enhancement

#1243 Upgrade to near-fastauth-wallet 2.0.1
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
Labels: feature

#1244 Remove Zendesk widget in favor of Gleap (2 of 2)
  .env.example
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/hooks/useGatewayEvents.ts
  src/pages/_app.tsx
  src/pages/documentation/[[...slug]].tsx
  src/utils/config.ts
Labels: enhancement

#1246 Update README for local VM dev flow
  README.md
Labels: documentation

#1247 FastAuth VM Support
  package.json
  pnpm-lock.yaml
Labels: enhancement

#1251 Jh/form wizard
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/FollowUp.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
  src/components/research-form-wizard/ResearchFormWizard.tsx
  src/components/research-form-wizard/StepLayout.tsx
  src/hooks/useResearchWizardEvents.tsx
  src/pages/_app.tsx
  src/stores/researchWizard.tsx
  src/utils/analytics.ts
Labels: feature

#1260 fix: adjust styles for form to scroll on select other on motivation page
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/FollowUp.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
  src/components/research-form-wizard/ResearchFormWizard.tsx
  src/components/research-form-wizard/StepLayout.tsx
Labels: bug

#1249 Change search
  package.json
  pnpm-lock.yaml
  src/components/Pagination.tsx
  src/components/lib/Input/Input.tsx
  src/components/lib/Input/index.ts
  src/components/lib/Input/styles.ts
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/FollowUp.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
  src/components/sidebar-navigation/Search.tsx
  src/components/sidebar-navigation/Search/AppsResults.tsx
  src/components/sidebar-navigation/Search/ComponentsResults.tsx
  src/components/sidebar-navigation/Search/DocsResults.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
  src/hooks/useDebounce.ts
  src/pages/_app.tsx
  src/pages/search.tsx
  src/stores/researchWizard.tsx
  src/utils/algoliaSearchApi.ts
  src/utils/catalogSearchApi.ts
Labels: enhancement

#1268 develop -> main
  package.json
  pnpm-lock.yaml
  src/components/Pagination.tsx
  src/components/lib/Input/Input.tsx
  src/components/lib/Input/index.ts
  src/components/lib/Input/styles.ts
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/FollowUp.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
  src/components/sidebar-navigation/Search.tsx
  src/components/sidebar-navigation/Search/AppsResults.tsx
  src/components/sidebar-navigation/Search/ComponentsResults.tsx
  src/components/sidebar-navigation/Search/DocsResults.tsx
  src/components/sidebar-navigation/Sidebar.tsx
  src/components/sidebar-navigation/SmallScreenHeader.tsx
  src/components/sidebar-navigation/styles.ts
  src/hooks/useDebounce.ts
  src/pages/_app.tsx
  src/pages/search.tsx
  src/stores/researchWizard.tsx
  src/utils/algoliaSearchApi.ts
  src/utils/catalogSearchApi.ts
Labels: ignore-for-release

#1269 Jh/rudderstack hot fix
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
Labels: bug

#1270 Rudderstack form submissions hotfix
  src/components/research-form-wizard/FormPages/Experience.tsx
  src/components/research-form-wizard/FormPages/Motivation.tsx
  src/components/research-form-wizard/FormPages/UserType.tsx
Labels: ignore-for-release
