Repository near/near-discovery, pull requests merged in 2024-01, with the labels that each got.

#899 fix: custom Link element should handle when href is undefined
  src/components/vm/VmInitializer.tsx
Labels: ignore-for-release

#900 fix link regression
  src/components/vm/VmInitializer.tsx
Labels: ignore-for-release

#902 Fixed code not showing after publish redirect to verify transaction
  src/components/sandbox/Sandbox.js
Labels: bug

#904 chore: sync to latest vm hotfix
  package.json
  pnpm-lock.yaml
Labels: dependency

#905 hotfix deploy
  .env.example
  package.json
  pnpm-lock.yaml
  src/components/sandbox/Sandbox.js
  src/components/vm/VmInitializer.tsx
  src/pages/signin.tsx
  src/utils/config.ts
Labels: ignore-for-release

#915 Fix: Session lost with MyNearWallet
  src/pages/signin.tsx
Labels: bug

#918 set a referrer policy header
  next.config.js
Labels: ignore-for-release

#921 chore: Updated wallet-selector to 8.9.2
  package.json
  pnpm-lock.yaml
Labels: dependency

#922 fix(headers): temporarily remove to fix issues resolving ipfs images
  next.config.js
Labels: bug

#923 pull a fix from develop
  next.config.js
Labels: ignore-for-release

#924 Specifies a referrer policy to ensure we pass the referrer to analytics
  next.config.js
Labels: ignore-for-release

#913 chore: update `idos-sdk` version to `0.0.30`
  package.json
  pnpm-lock.yaml
  src/pages/settings.tsx
  src/stores/idosStore.ts
Labels: enhancement

#925 develop -> main
  next.config.js
  package.json
  pnpm-lock.yaml
  src/pages/settings.tsx
  src/stores/idosStore.ts
Labels: ignore-for-release

#926 fix: fetch data from idOS
  src/components/vm/VmInitializer.tsx
  src/pages/settings.tsx
Labels: ignore-for-release

#927 chore: bump to the latest vm patch
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#928 develop -> main
  package.json
  pnpm-lock.yaml
  src/components/vm/VmInitializer.tsx
  src/pages/settings.tsx
Labels: ignore-for-release

#932 chore: bump to latest vm patch
  package.json
  pnpm-lock.yaml
Labels: dependency

#933 develop -> main
  package.json
  pnpm-lock.yaml
Labels: ignore-for-release

#940 chore: remove the now deprecated nearwallet
  src/components/vm/VmInitializer.tsx
Labels: enhancement

#939 chore: this project uses pnpm
  package.json
Labels: ignore-for-release

#938 chore(data): send user agent detail with anonymous usage data
  src/index.d.ts
  src/utils/analytics.ts
Labels: enhancement

#941 chore: remove the horizon banner since the cohort has already kicked off
  src/components/banner/Horizon.tsx
  src/components/navigation/desktop/DesktopNavigation.tsx
  src/components/navigation/mobile/Menu.tsx
Labels: enhancement

#949 chore: bump to latest vm patch
  package.json
  pnpm-lock.yaml
Labels: dependency

#950 develop -> main
  package.json
  pnpm-lock.yaml
  src/components/banner/Horizon.tsx
  src/components/navigation/desktop/DesktopNavigation.tsx
  src/components/navigation/mobile/Menu.tsx
  src/components/vm/VmInitializer.tsx
  src/index.d.ts
  src/utils/analytics.ts
Labels: ignore-for-release
