Repository near/near-discovery, pull requests merged in 2025-01, with the labels that each got.

#1349 Add static Privacy Policy page
  src/pages/privacy.tsx
Labels: feature

#1355 feat: newspage
  .env.example
  package.json
  pnpm-lock.yaml
  public/newsletter/00f47a7eee.jpg
  public/newsletter/138d590a7b.jpg
  public/newsletter/32.jpg
  public/newsletter/33.jpg
  public/newsletter/34.jpg
  public/newsletter/35.jpg
  public/newsletter/36.png
  public/newsletter/379eb76f0f.jpg
  public/newsletter/4824296aee.jpg
  public/newsletter/d1bd3e0fc0.jpg
  src/components/scrollToTop.tsx
  src/config.ts
  src/pages/api/newsletter/[id].ts
  src/pages/api/newsletter/index.ts
  src/pages/api/newsletter/subscribe.ts
  src/pages/newsletter.tsx
Labels: feature

#1356 Fix/minor visual error
  src/components/sidebar-navigation/styles.ts
  src/components/wallet-utilities/SendNear.tsx
  src/pages/index.tsx
  src/pages/privacy.tsx
Labels: bug

#1336 feature: add brand new tool for creating DAOs & Multisigs
  src/components/tools/DecentralizedOrganization/CreateDaoForm.tsx
  src/components/tools/DecentralizedOrganization/ListDao.tsx
  src/components/tools/DecentralizedOrganization/index.tsx
  src/components/tools/Multisig/CreateMultisigForm.tsx
  src/components/tools/Multisig/index.tsx
  src/components/tools/Shared/LabelWithTooltip.tsx
  src/config.ts
  src/pages/tools.tsx
  src/utils/types.ts
Labels: feature

#1358 fix: Display Balance in Wallet Utils
  src/components/wallet-utilities/SendNear.tsx
Labels: bug

#1365 fix: subscribe form
  src/components/scrollToTop.tsx
  src/config.ts
  src/pages/api/newsletter/subscribe.ts
  src/pages/newsletter.tsx
Labels: bug

#1368 Fix: redirects
  next.config.js
  src/pages/[...arbitrary].tsx
Labels: ignore-for-release
